orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration

version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  build:
    docker:
      — image: circleci/node@3.0.0
    working_directory: ~/repo
    steps:
        — checkout
        - run:
          name: install-npm
          command: npm install
        - run:
            name: test
            command: yarn test